name: scp files
on:
  push:
    branches:
      - add-to-invoice

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
      - run: npm i
      - run: npm run test
      - run: npm run build

        with:
          host: root@165.232.156.60:/var/www/hourlyprice.io
          username: root
          password: 3KacLbKUc59CmsGC
          port: 22
          source: ./build/*
          target: /public_html
