name: scp files
on:
  push:
    branches:
      - add-to-invoice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: root@165.232.156.60:/var/www/hourlyprice.io/public_html
          username: root
          password: 3KacLbKUc59CmsGC
          port: 22
          source: "deploy.tar"
